# codecov.yml (à la racine du repo)
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%     # tolérance petites variations

ignore:
  - "tests/**"
  - "benchmarks/**"
  - "**/*.g.cs"
  - "**/*.designer.cs"

# Aide Codecov à remapper les chemins si besoin (runner Linux)
fixes:
  - "/home/runner/work/FastGeoMesh/FastGeoMesh/::"
