name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: PR Build / Test / Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore --use-lock-file

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: dotnet test --configuration Release --no-build --collect "Xplat Code Coverage" --results-directory coverage

      - name: Extract coverage (for summary only)
        shell: bash
        run: |
          report=$(find coverage -name 'coverage.cobertura.xml' | head -n 1)
          if [ -f "$report" ]; then
            lineRate=$(xmllint --xpath 'string(/coverage/@line-rate)' "$report" 2>/dev/null || echo "0")
            pct=$(awk -v r="$lineRate" 'BEGIN{ if(r==""||r=="NaN") r=0; printf("%.2f", r*100); }')
            echo "Coverage: ${pct}%" >> $GITHUB_STEP_SUMMARY
          else
            echo "Coverage: 0%" >> $GITHUB_STEP_SUMMARY
          fi
