name: ci

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ['**']
  push:
    branches: ['**']
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-test-docs:
    name: Build / Test / Coverage / Docs
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.line_rate }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test with coverage
        run: dotnet test --configuration Release --no-build --collect "Xplat Code Coverage" --results-directory coverage

      - name: Extract coverage percentage
        id: coverage
        shell: bash
        run: |
          report=$(find coverage -name 'coverage.cobertura.xml' | head -n 1)
          if [ -f "$report" ]; then
            lineRate=$(xmllint --xpath 'string(/coverage/@line-rate)' "$report" 2>/dev/null || echo "0")
            pct=$(python -c "rate=float('${lineRate:-0}');print(f'
