name: CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test with coverage
        run: >-
          dotnet test --configuration Release --no-build
          /p:CollectCoverage=true
          /p:CoverletOutputFormat=opencover\,lcov
          /p:CoverletOutput=tests/FastGeoMesh.Tests/TestResults/coverage/
          /p:Threshold=80 /p:ThresholdType=line,branch,method /p:ThresholdStat=Total
      - name: Upload coverage artifact (LCOV)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: tests/FastGeoMesh.Tests/TestResults/coverage/coverage.info
          if-no-files-found: warn
      - name: Upload coverage artifact (OpenCover)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-opencover
          path: tests/FastGeoMesh.Tests/TestResults/coverage/coverage.opencover.xml
          if-no-files-found: warn
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: tests/FastGeoMesh.Tests/TestResults/coverage/coverage.info
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          disable_search: true
          name: fastgeomesh-coverage
