name: CI

on:
  push:
    branches: [master, main, develop]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/wiki-sync.yml"
      - "**/*.md"
  pull_request:
    branches: [master, main, develop]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Check one type per file
        run: python3 scripts/check_one_type_per_file.py

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Verify formatting
        run: dotnet format --verify-no-changes

      - name: Test with coverage (Cobertura)
        run: |
          dotnet test --configuration Release --no-build \
            --collect:"XPlat Code Coverage" \
            --settings tests/coverlet.runsettings \
            --results-directory ./TestResults \
            --logger trx \
            --verbosity normal

      - name: Debug Coverage Files
        if: always()
        run: |
          echo "=== Searching for coverage files (.trx/.cobertura.xml) ==="
          find . -path "*/TestResults/*" -name "*.trx" -o -name "coverage.cobertura.xml" -print || true
          echo "=== Listing ./TestResults (if exists) ==="
          ls -la ./TestResults || echo "TestResults directory not found"

      - name: Upload test results (TRX)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-trx
          path: "**/TestResults/**/*.trx"
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload coverage artifacts (Cobertura)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-cobertura
          path: |
            **/TestResults/**/coverage.cobertura.xml
            **/coverage.cobertura.xml
          if-no-files-found: error
          retention-days: 7

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: |
            **/TestResults/**/coverage.cobertura.xml
            **/coverage.cobertura.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
          name: fastgeomesh-coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
