name: publish

on:
  push:
    tags:
      - 'v*'    # ex: v1.2.3

permissions:
  contents: read

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: ver
        run: |
          TAG="${GITHUB_REF##*/}"           # v1.2.3
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "pkg=${TAG#v}" >> $GITHUB_OUTPUT  # 1.2.3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          dotnet pack src/FastGeoMesh/FastGeoMesh.csproj -c Release \
            -p:PackageVersion=${{ steps.ver.outputs.pkg }} \
            -p:ContinuousIntegrationBuild=true \
            -o artifacts

      - name: Publish NuGet package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          ls -1 artifacts
          for pkg in artifacts/*.nupkg; do
            echo "Publishing $pkg"
            dotnet nuget push "$pkg" --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json --skip-duplicate
          done
